apiVersion: apps/v1
kind: Deployment
metadata:
  name: jdev-web
  namespace: justin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jdev
      role: web
  template:
    metadata:
      labels:
        app: jdev
        role: web
    spec:
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      containers:
        - name: jdev-web
          image: jdev:1.0.0
          args:
            - '--bind'
            - '0.0.0.0'
            - 'app:app'
          ports:
            - name: gunicorn
              containerPort: 8000
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              port: gunicorn
              path: /
          livenessProbe:
            initialDelaySeconds: 10
            exec:
              command:
                - /bin/sh
                - -c 
                - "pidof -x gunicorn"
