apiVersion: batch/v1
kind: Job
metadata:
  name: jdev-job
  namespace: justin
spec:
  template:
    metadata:
      labels:
        app: jdev
        role: jdev-job
    spec:
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      restartPolicy: OnFailure
      containers:
        - name: justin-jdev-job
          image: jdev:1.0.0
          command:
            - python3
          args:
            - cli.py
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
