apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jdev-basic
  namespace: justin
spec:
  chart:
    spec:
      version: ">=1.0.0"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: jdev.staging
          paths:
            - path: /
              pathType: ImplementationSpecific
